### ISSUE TITLE
Current node v0.5.10-pre doesnt like it

### ISSUE THREAD

**Issue by alangrus** [treygriffith/connect-mongodb#40]
Looks like a version ahead problem.

node -v
v0.5.10-pre

npm install connect-mongodb
  npm ERR! Not compatible with your version of node/npm: connect@1.5.1
  npm ERR! Required: {"node":">= 0.4.1 < 0.5.0"}
  npm ERR! Actual:   {"npm":"1.0.100","node":"0.5.10-pre"}

**Comment by ryandesign** [comment]
node 0.6.0 has been released. Please fix this issue by using newer versions of the dependencies.

**Comment by masylum** [comment]
done

**Comment by ryandesign** [comment]
Thank you for the update, but the issue is not resolved. connect-mongodb 1.1.0 still declares a dependency on connect 1.5.1, which declares that it requires node 0.4.x; please update connect-mongodb to use a newer version of connect that does not have this restriction.

The engines line that was removed from connect-mongodb's package.json file in 1.1.0 should probably be put back in.

**Comment by ryandesign** [comment]
Ah, I see it's since been resolved by updating to connect 1.7.2 in 148ca015e59ce011bd6a50fc51833f151973b998 and updating connect-mongodb's version to 1.1.1 in a771063a6d0025c9e9b42dd32e342cf8034d4286. I wish you had mentioned that here so I would have been notified of this. :)

It might still be useful for other reasons to reinstate the "engines" line in the package.json file.
